sudo: false
os:
    - linux
    - osx
language: python
branches:
    except:
    - gh-pages
env:
    matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=checkers
    - DOC=sphinx
      allow_failures:
      - env: TOXENV=pypy
      - env: TOXENV=checkers
install:
- pip install tox
- if [[ $TOXENV == 'checkers' ]]; then pip install flake8; fi 
- if [[ $TOXENV == 'checkers' ]]; then pip install pep8-naming; fi 
- if [[ $TOXENV == 'py27' ]]; then pip install coveralls; fi 
- if [[ $TOXENV == 'py27' ]]; then pip install isbnlib; fi 
- if [[ $DOC == 'sphinx' ]]; then pip install sphinx; fi 
script:
- if [[ ! -z $TOXENV ]]; then tox -e $TOXENV; fi 
- if [[ $DOC == 'sphinx' ]]; then cd docs; sphinx-build -n -b html -d _build/.doctrees . _build/html; fi
after_success:
- if [[ $TOXENV == 'py27' ]]; then coveralls; fi
