sudo: false
language: python
branches:
  only:
    - v4.3.21
#   - dev
#   - master
# os:
#   - linux
#   - osx
matrix:
  include:
    - os: osx
      language: generic
      env: TOXENV=py36
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=checkers
    - python: "3.5"
      env: DOC=sphinx
    - python: "3.6"
      env: TOXENV=plugins
    - python: "3.6"
      env: ENV=dev
    - python: "nightly"
      env: TOXENV=nightly
    - python: "3.6"
      env: TOXENV=speed
    - dist: xenial
      language: python
      python: 3.7
      env: TOXENV=py37
  allow_failures:
    - env: TOXENV=py27
    - env: TOXENV=nightly
    - env: ENV=dev
install:
  # - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew upgrade python; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pip3 install tox; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then pip install tox; fi
  - if [[ $TOXENV == 'checkers' ]]; then pip install flake8; fi
  - if [[ $TOXENV == 'checkers' ]]; then pip install pep8-naming; fi
  - if [[ $TOXENV == 'py35' ]]; then pip install coveralls; fi
  - if [[ $DOC == 'sphinx' ]]; then pip install sphinx; fi
script:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]] && [[ $TOXENV == 'py36' ]]; then python3 setup.py install && isbn_conf cachepath; fi
  - if [[ ! -z $TOXENV ]]; then tox -e $TOXENV -c tox.ini; fi
  - if [[ $ENV == 'dev' ]]; then tox -e py36 -c tox-dev.ini; fi
  - if [[ $DOC == 'sphinx' ]]; then cd docs; sphinx-build -n -b html -d _build/.doctrees . _build/html; fi
after_success:
  - if [[ $TOXENV == 'py35' ]]; then coveralls; fi
notifications:
  email:
    on_success: never
    on_failure: always
