language: python
env:
- TOXENV=py26
- TOXENV=py27
- TOXENV=py33
- TOXENV=flake8
matrix:
  allow_failures:
  - env: TOXENV=flake8
install:
- pip install tox
- pip install flake8
- pip install coveralls 
script:
- tox -e $TOXENV
after_success:
  coveralls
