language: python
env:
- TOXENV=py26
- TOXENV=py27
- TOXENV=py33
- TOXENV=py34
- TOXENV=pypy
- TOXENV=flake8
matrix:
  allow_failures:
  - env: TOXENV=flake8
  - env: TOXENV=pypy
  - env: TOXENV=py34
  - env: TOXENV=py26
  - env: TOXENV=py33
install:
- pip install tox
- pip install flake8
- pip install coveralls 
script:
- tox -e $TOXENV
after_success:
  coveralls
