sudo: false
os:
    - linux
    - osx
language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
branches:
    except:
    - gh-pages
env:
- TOXENV=py26
- TOXENV=py27
- TOXENV=py33
- TOXENV=py34
- TOXENV=pypy
- TOXENV=checkers
- DOC=sphinx
matrix:
  allow_failures:
  - env: TOXENV=pypy
  - env: TOXENV=checkers
install:
- pip install tox
- pip install flake8
- pip install pep8-naming
- pip install coveralls
- pip install sphinx
- pip install isbnlib
script:
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' && $TOXENV == 'py26' ]]; then tox -e $TOXEVEN; fi 
- if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $TOXENV == 'py27' ]]; then tox -e $TOXEVEN; fi 
- if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $TOXENV == 'checkers' ]]; then tox -e $TOXEVEN; fi 
- if [[ $TRAVIS_PYTHON_VERSION == '3.3' && $TOXENV == 'py33' ]]; then tox -e $TOXEVEN; fi 
- if [[ $TRAVIS_PYTHON_VERSION == '3.4' && $TOXENV == 'py34' ]]; then tox -e $TOXEVEN; fi 
- if [[ $TRAVIS_PYTHON_VERSION == 'pypy' && $TOXENV == 'pypy' ]]; then tox -e $TOXEVEN; fi 
- if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $DOC == 'sphinx' ]]; then cd docs; sphinx-build -n -b html -d _build/.doctrees . _build/html; fi"
after_success:
- if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $TOXENV == 'py27' ]]; then coveralls; fi
