language: python
env:
- TOXENV=py26
- TOXENV=py27
- TOXENV=py33
- TOXENV=py34
- TOXENV=pypy
- TOXENV=flake8
matrix:
  allow_failures:
  - env: TOXENV=pypy
install:
- pip install tox
- pip install flake8
- pip install pep8-naming
- pip install coveralls
script:
- tox -e $TOXENV
after_success:
- "if [[ $TOXENV == 'py27' ]]; then coveralls; fi"
